# excluded:
#   - DerivedData

# disabled_rules:
#   - orphaned_doc_comment

# force_cast: warning # warning or error

# identifier_name: # 2
#   excluded:
#     - i
#     - id
#     - x
#     - y
#     - z

# line_length:
#   ignores_urls: true
#   ignores_function_declarations: true
#   ignores_comments: true

# function_body_length:
#     warning: 300
#     error: 500

# function_parameter_count:
#     warning: 6
#     error: 8
    
# type_body_length:
#     warning: 300
#     error: 500
    
# file_length:
#     warning: 1000
#     error: 1500
#     ignore_comment_only_lines: true
    
# cyclomatic_complexity:
#     warning: 15
#     error: 25

# opt_in_rules:
#   - indentation_width
#   - force_unwrapping
#   - redundant_type_annotation
#   - force_try
#   - operator_usage_whitespace

# indentation_width:
#   indentation_width: 2

# custom_rules:
#   array_constructor: # 1
#     name: "Array/Dictionary initializer" # 2
#     regex: '[let,var] .+ = (\[.+\]\(\))' # 3
#     capture_group: 1 # 4
#     message: "Use explicit type annotation when initializing empty arrays and dictionaries" # 5
#     severity: warning # 6

# reporter: "xcode"

excluded:
  - ${PWD}/Carthage
  - ${PWD}/Pods
  - ${PWD}/DerivedData

disabled_rules:
  - discarded_notification_center_observer
  - notification_center_detachment
  - orphaned_doc_comment
  - todo
  - trailing_whitespace
  - vertical_whitespace_opening_braces
  - vertical_whitespace_closing_braces
  - comment_spacing

analyzer_rules:
  - unused_import

opt_in_rules:
  - array_init
  - attributes
  - closure_end_indentation
  - closure_spacing
  - collection_alignment
  - colon # promote to error
  - convenience_type
  - discouraged_object_literal
  - empty_collection_literal
  - empty_count
  - empty_string
  - enum_case_associated_values_count
  - fatal_error_message
  - first_where
  - force_unwrapping
  - implicitly_unwrapped_optional
  - indentation_width
  - last_where
  - legacy_random
  - literal_expression_end_indentation
  - multiline_arguments
  - multiline_function_chains
  - multiline_literal_brackets
  - multiline_parameters
  - multiline_parameters_brackets
  - operator_usage_whitespace
  - overridden_super_call
  - pattern_matching_keywords
  - prefer_self_type_over_type_of_self
  - redundant_nil_coalescing
  - redundant_type_annotation
  - strict_fileprivate
  - toggle_bool
  - trailing_closure
  - unneeded_parentheses_in_closure_argument
  - vertical_whitespace_closing_braces
  - vertical_whitespace_opening_braces
  - yoda_condition


custom_rules:
  array_constructor:
    name: "Array/Dictionary initializer"
    regex: '[let,var] .+ = (\[.+\]\(\))'
    capture_group: 1
    message: "Use explicit type annotation when initializing empty arrays and dictionaries"
    severity: warning


attributes:
  always_on_same_line:
    - "@IBSegueAction"
    - "@IBAction"
    - "@NSManaged"
    - "@objc"

force_cast: warning
force_try: warning
function_body_length:
    warning: 300

legacy_hashing: error

identifier_name:
  excluded:
    - i
    - id
    - x
    - y
    - z

indentation_width:
  indentation_width: 4

line_length:
  ignores_urls: true
  ignores_function_declarations: true
  ignores_comments: true

multiline_arguments:
  first_argument_location: next_line
  only_enforce_after_first_closure_on_first_line: true
  
private_over_fileprivate:
  validate_extensions: true

# trailing_whitespace:
#   ignores_empty_lines: false
#   ignores_comments: true

vertical_whitespace:
  max_empty_lines: 3